version: '3.9'

services:

  notesdb:
    container_name: notesdb
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
