openapi: 3.0.0
info:
  version: 1.0.0
  title: Note Taking API
  description: API for a note-taking application
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/notes:
    post:
      tags:
        - notes
      summary: Create a new note
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInputDto'
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteDto'
  /api/notes/all:
    get:
      tags:
        - notes
      summary: Get all notes
      operationId: getAllNotes
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteDto'
  /api/notes/{id}:
    get:
      tags:
        - notes
      summary: Get a note by ID
      operationId: getNoteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteDto'
        '404':
          description: Note not found
    put:
      tags:
        - notes
      summary: Update an existing note
      operationId: updateNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInputDto'
      responses:
        '200':
          description: Note updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteDto'
        '404':
          description: Note not found
    delete:
      tags:
        - notes
      summary: Delete a note
      operationId: deleteNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Note deleted
        '404':
          description: Note not found

components:
  schemas:
    NoteDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content

    NoteInputDto:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content